#docker-compose.yml

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      -"8000:8000"
    env_file:
      - .env
    depends_on:
      - db

    db:
      image: postgres:15
      volumes:
       - db_data:/var/lib/postgresql/db_data
      environment:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
      ports:
       - "5432:5432"

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
     - ./frontend:/app
     - /app/node_modules
    working_dir: /app
    command: nmp start

volumes:
  db_data: